#Placeholder for converting points and paths generated by this code for use in Panda3D.

def convertPoint(point, size):
    
    row, col = point
    #We must output the points for use on a Cartesian coordinate system
    x = col - size[1]/2.0  # A grid with n columns spans from -(n/2) to (n/2)
    y = row - size[0]/2.0  # A grid with m rows spans from -(n/2) to (n/2)
    return (x,y)

def convertPath(path):
    pass